/*
 * Engli grammar bank.
 * The bank is deliberately data-driven: append another entry to grammarBank
 * and the player, statistics and total counter will include it automatically.
 */
const grammarBank = [
  ["Inversion & emphasis", "_____ had I left the office when it started to rain.", ["Hardly", "Only", "Even", "Still"], 0, "Hardly is followed by auxiliary + subject and pairs with when."],
  ["Inversion & emphasis", "_____ did the train arrive than the doors opened.", ["No sooner", "Only then", "Rarely", "Little"], 0, "No sooner is used with did + subject + verb and than."],
  ["Inversion & emphasis", "_____ do we see such careful research in a short report.", ["Rarely", "Not only", "No sooner", "Only after"], 0, "A negative or limiting adverbial at the front triggers inversion."],
  ["Inversion & emphasis", "_____ was the proposal costly, but it was also difficult to implement.", ["Not only", "Only", "Hardly", "Never"], 0, "Not only at the beginning is followed by inverted auxiliary and subject."],
  ["Inversion & emphasis", "_____ should confidential files be left on a public desk.", ["Under no circumstances", "Only after", "Little", "Not until"], 0, "Under no circumstances requires inversion in this formal structure."],
  ["Inversion & emphasis", "_____ did she know that the decision would change her career.", ["Little", "Only", "No sooner", "Never before"], 0, "Little did she know is a fixed emphatic inversion."],
  ["Inversion & emphasis", "Only after the audit had finished _____ the managers understand the risk.", ["did", "had", "were", "would"], 0, "Only after at the beginning places the auxiliary before the subject."],
  ["Inversion & emphasis", "Seldom _____ I encountered such an effective solution.", ["have", "did", "was", "am"], 0, "Seldom is a fronted negative adverbial, so have comes before I."],
  ["Inversion & emphasis", "Never before _____ the city faced such severe flooding.", ["had", "did", "has", "was"], 0, "Past perfect is needed for an earlier experience before the reference point."],
  ["Inversion & emphasis", "Not until midnight _____ the missing files found.", ["were", "had", "did", "have"], 0, "Not until triggers inversion; the passive verb agrees with files."],
  ["Inversion & emphasis", "Were it not for your advice, I _____ the wrong conclusion.", ["would reach", "will reach", "had reached", "reach"], 0, "Were it not for introduces a hypothetical present condition."],
  ["Inversion & emphasis", "Had I known about the delay, I _____ earlier.", ["would have left", "will leave", "would leave", "left"], 0, "Had I known is an inverted third conditional."],
  ["Inversion & emphasis", "Should you need assistance, _____ the reception desk.", ["contact", "contacted", "contacting", "to contact"], 0, "Should you need is a formal inverted first conditional; use the base verb."],
  ["Inversion & emphasis", "So demanding _____ the course that several students withdrew.", ["was", "did", "had", "would"], 0, "So + adjective at the beginning is followed by inverted be."],
  ["Inversion & emphasis", "Such _____ the confusion that nobody knew who was responsible.", ["was", "did", "had", "would"], 0, "Such was the confusion is a fixed emphatic pattern."],
  ["Inversion & emphasis", "At no point _____ the report claim that the system was unsafe.", ["did", "was", "had", "has"], 0, "At no point triggers inversion with the past simple report."],
  ["Inversion & emphasis", "Nowhere else _____ you find a view like this one.", ["can", "do", "are", "have"], 0, "Nowhere else is a negative place adverbial followed by can + subject."],
  ["Inversion & emphasis", "Only by working together _____ we solve the problem.", ["can", "will", "did", "have"], 0, "Only by + -ing takes modal inversion in the main clause."],
  ["Inversion & emphasis", "On no account _____ visitors allowed to enter the laboratory.", ["are", "do", "have", "will"], 0, "On no account requires inversion; visitors are allowed is passive."],
  ["Inversion & emphasis", "Had it not been for the scholarship, she _____ her studies.", ["could not have continued", "cannot continue", "would not continue", "did not continue"], 0, "Had it not been for refers to an unreal past condition."],

  ["Conditionals", "If I _____ you, I would ask for a second opinion.", ["were", "was", "am", "had been"], 0, "Were is the formal form used in an unreal present condition."],
  ["Conditionals", "If she had left earlier, she _____ the last train.", ["would have caught", "will catch", "would catch", "caught"], 0, "This is a third conditional about an unreal past result."],
  ["Conditionals", "Unless you back up the files, you _____ them.", ["may lose", "would lose", "had lost", "lost"], 0, "Unless means if not and takes a present condition with a possible result."],
  ["Conditionals", "Provided that the weather improves, the event _____ outdoors.", ["will take place", "would take place", "took place", "had taken place"], 0, "Provided that introduces a real future condition."],
  ["Conditionals", "Had we known about the road closure, we _____ another route.", ["would have taken", "will take", "would take", "took"], 0, "Had we known is the inverted form of a third conditional."],
  ["Conditionals", "Were the company to relocate, many employees _____ remotely.", ["would work", "will work", "worked", "had worked"], 0, "Were + subject + to-infinitive describes a hypothetical future."],
  ["Conditionals", "If he had listened to the warning, he _____ in trouble now.", ["would not be", "would not have been", "will not be", "was not"], 0, "This mixed conditional links an unreal past cause to a present result."],
  ["Conditionals", "If I had more time, I _____ another language.", ["would learn", "will learn", "would have learned", "learned"], 0, "The unreal present condition takes would + base verb."],
  ["Conditionals", "As long as you submit the form today, your application _____ considered.", ["will be", "would be", "was", "had been"], 0, "As long as sets a real condition for a future passive result."],
  ["Conditionals", "If it _____ for public transport, the city would be far less accessible.", ["weren't", "hadn't been", "isn't", "wouldn't be"], 0, "If it weren't for refers to an unreal present situation."],
  ["Conditionals", "Suppose the plan failed. What _____ you do next?", ["would", "will", "did", "had"], 0, "Suppose introduces a hypothetical situation followed by would."],
  ["Conditionals", "But for your help, I _____ the deadline.", ["could not have met", "cannot meet", "would not meet", "did not meet"], 0, "But for means if it had not been for in this unreal past context."],
  ["Conditionals", "If she _____ so tired, she would join us for dinner.", ["weren't", "hadn't been", "isn't", "wouldn't be"], 0, "The condition is unreal in the present, so use were."],
  ["Conditionals", "If the figures are accurate, the project _____ profitable.", ["will be", "would be", "would have been", "was"], 0, "A first conditional uses present simple in the if-clause and will in the result."],
  ["Conditionals", "If he had been told, he _____ have objected.", ["might", "must", "should", "can"], 0, "Might have expresses a possible unreal past result."],
  ["Conditionals", "Should the situation worsen, we _____ the emergency plan.", ["will activate", "would activate", "activated", "had activated"], 0, "Should the situation worsen is a formal first conditional."],
  ["Conditionals", "If I had remembered to charge my phone, I _____ lost.", ["would not have got", "will not get", "would not get", "did not get"], 0, "The past perfect condition takes would have + past participle."],
  ["Conditionals", "I wish I _____ more notes during the lecture.", ["had taken", "took", "would take", "have taken"], 0, "Wish about a past regret takes the past perfect."],
  ["Conditionals", "It is time you _____ responsibility for the decision.", ["took", "take", "had taken", "would take"], 0, "It is time is followed by a past form for present criticism."],
  ["Conditionals", "I would rather you _____ this information with anyone else.", ["did not share", "not share", "had not shared", "would not share"], 0, "Would rather about another person's present action takes past simple."],

  ["Modals & deduction", "She _____ have forgotten the appointment; she never misses one.", ["must", "should", "can", "would"], 0, "Must have expresses a strong deduction about the past."],
  ["Modals & deduction", "They _____ have been at home because all the lights were off.", ["can't", "mustn't", "shouldn't", "needn't"], 0, "Can't have been expresses a strong negative deduction."],
  ["Modals & deduction", "He _____ have left already; his coat is missing.", ["might", "mustn't", "needn't", "shouldn't"], 0, "Might have expresses a possibility about the past."],
  ["Modals & deduction", "The parcel _____ have arrived by now.", ["should", "must", "can", "would"], 0, "Should have arrived expresses an expected result by now."],
  ["Modals & deduction", "You _____ have brought any food; there is plenty here.", ["needn't", "mustn't", "couldn't", "wouldn't"], 0, "Needn't have brought means the past action was unnecessary."],
  ["Modals & deduction", "The figures _____ to be accurate, but we should verify them.", ["ought", "must", "can", "would"], 0, "Ought to expresses a reasonable expectation."],
  ["Modals & deduction", "That noise _____ be the heating system starting up.", ["could", "must", "should", "would"], 0, "Could be presents one possible explanation."],
  ["Modals & deduction", "With better planning, the launch _____ more successful.", ["would have been", "will be", "is", "has been"], 0, "Would have been describes an unreal past result."],
  ["Modals & deduction", "She _____ not have noticed the change in the timetable.", ["may", "must", "should", "would"], 0, "May not have expresses a past possibility."],
  ["Modals & deduction", "He _____ be working late; his office light is still on.", ["must", "should", "can", "would"], 0, "Must be working is a strong deduction about the present."],
  ["Modals & deduction", "You _____ be serious. That solution would cost twice as much.", ["can't", "mustn't", "needn't", "shouldn't"], 0, "Can't be serious expresses disbelief about the present."],
  ["Modals & deduction", "You _____ worry about the tickets; I have already booked them.", ["needn't", "mustn't", "couldn't", "wouldn't"], 0, "Needn't expresses a lack of present necessity."],
  ["Modals & deduction", "The repairs _____ be completed by Friday.", ["should", "can", "would", "mustn't"], 0, "Should be completed expresses an expected passive result."],
  ["Modals & deduction", "The files _____ have been damaged during the transfer.", ["might", "mustn't", "needn't", "wouldn't"], 0, "Might have been damaged expresses a possible past event."],
  ["Modals & deduction", "We _____ have avoided the delay if we had checked the schedule.", ["could", "must", "should", "need"], 0, "Could have avoided expresses a past possibility that did not happen."],
  ["Modals & deduction", "All applicants _____ to submit two references.", ["have", "must", "should", "ought"], 0, "Have to expresses an external requirement."],
  ["Modals & deduction", "Employees _____ to complete the training before starting.", ["are supposed", "are able", "are likely", "are willing"], 0, "Are supposed to expresses an expected rule or arrangement."],
  ["Modals & deduction", "The report _____ have been sent to the wrong department.", ["should", "mustn't", "needn't", "would"], 0, "Should have been sent expresses what was expected to happen."],
  ["Modals & deduction", "Staff _____ disclose client information without permission.", ["mustn't", "don't have to", "couldn't", "wouldn't"], 0, "Mustn't expresses prohibition."],
  ["Modals & deduction", "I _____ rather not discuss the matter until tomorrow.", ["would", "should", "could", "must"], 0, "Would rather is followed by the base verb for a preference."],

  ["Verb patterns", "The committee decided to _____ the proposal.", ["revise", "revising", "revised", "revision"], 0, "Decide is followed by a to-infinitive."],
  ["Verb patterns", "She avoids _____ late whenever possible.", ["working", "to work", "work", "worked"], 0, "Avoid is followed by a gerund."],
  ["Verb patterns", "The evidence made me _____ my initial conclusion.", ["reconsider", "to reconsider", "reconsidering", "reconsidered"], 0, "Make + object is followed by a bare infinitive in the active voice."],
  ["Verb patterns", "The manager let him _____ early.", ["leave", "to leave", "leaving", "left"], 0, "Let is followed by an object and a bare infinitive."],
  ["Verb patterns", "I would rather _____ at home tonight.", ["stay", "to stay", "staying", "stayed"], 0, "Would rather is followed by the base form."],
  ["Verb patterns", "They suggested _____ the meeting until Monday.", ["postponing", "to postpone", "postpone", "postponed"], 0, "Suggest is followed by a gerund or a that-clause, not a to-infinitive."],
  ["Verb patterns", "Remember _____ the side door before you leave.", ["to lock", "locking", "lock", "locked"], 0, "Remember to do something refers to a duty that has not happened yet."],
  ["Verb patterns", "I remember _____ that gallery when I was a child.", ["visiting", "to visit", "visit", "visited"], 0, "Remember doing something refers to a recalled past experience."],
  ["Verb patterns", "We regret _____ you that your application was unsuccessful.", ["to inform", "informing", "inform", "informed"], 0, "Regret to inform is a formal expression used before bad news."],
  ["Verb patterns", "She regrets _____ such a harsh comment.", ["making", "to make", "make", "made"], 0, "Regret doing something refers to a past action that is regretted."],
  ["Verb patterns", "He failed _____ the significance of the figures.", ["to notice", "noticing", "notice", "noticed"], 0, "Fail is followed by a to-infinitive."],
  ["Verb patterns", "I cannot help _____ when he tells that story.", ["laughing", "to laugh", "laugh", "laughed"], 0, "Cannot help is followed by a gerund."],
  ["Verb patterns", "We look forward to _____ from you soon.", ["hearing", "hear", "have heard", "be heard"], 0, "In look forward to, to is a preposition and takes a gerund."],
  ["Verb patterns", "She is used to _____ under pressure.", ["working", "work", "worked", "have worked"], 0, "Be used to means be accustomed to, so to is a preposition here."],
  ["Verb patterns", "The scheme allows employees _____ flexible hours.", ["to work", "working", "work", "worked"], 0, "Allow + object is followed by a to-infinitive."],
  ["Verb patterns", "It took him months to get used to _____ at night.", ["waking", "wake", "woke", "have woken"], 0, "Get used to is followed by a noun or gerund."],
  ["Verb patterns", "They persuaded her _____ for the position.", ["to apply", "applying", "apply", "applied"], 0, "Persuade + object is followed by a to-infinitive."],
  ["Verb patterns", "He denied _____ the confidential document.", ["having taken", "to take", "take", "taken"], 0, "Deny is followed by a gerund; perfect form places the action earlier."],
  ["Verb patterns", "The tutor encouraged us _____ in the discussion.", ["to participate", "participating", "participate", "participated"], 0, "Encourage + object is followed by a to-infinitive."],
  ["Verb patterns", "The director had the technician _____ the security system.", ["check", "to check", "checking", "checked"], 0, "Have + object + bare infinitive expresses arranged work in the active voice."],

  ["Tense & aspect", "She _____ at the company since 2018.", ["has been working", "is working", "worked", "had worked"], 0, "The present perfect continuous links an activity that began in the past to now."],
  ["Tense & aspect", "They _____ for an hour when the bus finally arrived.", ["had been waiting", "have waited", "were waiting", "waited"], 0, "Past perfect continuous shows duration before a past event."],
  ["Tense & aspect", "By next June, we _____ the bridge.", ["will have finished", "finish", "will finish", "finished"], 0, "Future perfect describes an action completed by a future time."],
  ["Tense & aspect", "When I called, the guests _____ already.", ["had left", "have left", "were leaving", "leave"], 0, "Past perfect places the departure before another past action."],
  ["Tense & aspect", "The policy _____ several times since it was introduced.", ["has been revised", "is revised", "was revising", "had revised"], 0, "Present perfect passive describes repeated changes up to now."],
  ["Tense & aspect", "He _____ constantly interrupting the speaker.", ["is", "has", "was", "has been"], 0, "Present continuous with constantly can express repeated irritating behaviour."],
  ["Tense & aspect", "What _____ you been doing since breakfast?", ["have", "did", "are", "were"], 0, "Present perfect continuous uses have + subject + been + -ing."],
  ["Tense & aspect", "The train _____ to arrive at 8:15, but it was delayed.", ["was supposed", "has supposed", "is supposing", "had supposed"], 0, "Was supposed to describes a past expectation or timetable."],
  ["Tense & aspect", "At this time tomorrow, I _____ across the Atlantic.", ["will be flying", "will have flown", "fly", "flew"], 0, "Future continuous describes an action in progress at a future time."],
  ["Tense & aspect", "It was the first time she _____ such a complex case.", ["had seen", "has seen", "saw", "was seeing"], 0, "After It was the first time, past perfect is the standard form."],
  ["Tense & aspect", "The results _____ just been announced.", ["have", "are", "were", "had"], 0, "Present perfect passive uses have been + past participle."],
  ["Tense & aspect", "_____ you use to live near the university?", ["Did", "Were", "Have", "Had"], 0, "Questions with used to use did + subject + use to."],
  ["Tense & aspect", "We _____ each other for more than ten years.", ["have known", "are knowing", "knew", "had known"], 0, "Know is stative and takes present perfect for a continuing relationship."],
  ["Tense & aspect", "It _____ all morning, so the ground is soaked.", ["has been raining", "rained", "was raining", "had rained"], 0, "Present perfect continuous explains a present result of recent activity."],
  ["Tense & aspect", "While the lawyers _____ the terms, the client waited outside.", ["were discussing", "have discussed", "discuss", "had discussed"], 0, "Past continuous describes an action in progress around a past moment."],
  ["Tense & aspect", "By 2030, she _____ in the field for twenty years.", ["will have been working", "will work", "has worked", "worked"], 0, "Future perfect continuous emphasizes duration up to a future point."],
  ["Tense & aspect", "The conference _____ because of the transport strike.", ["had been postponed", "has postponed", "was postponing", "postpones"], 0, "Past perfect passive shows the postponement happened before another past reference."],
  ["Tense & aspect", "The lecture _____ in five minutes, so please take a seat.", ["is about to start", "has started", "was starting", "would start"], 0, "Be about to describes an event that will happen very soon."],
  ["Tense & aspect", "The role of technology _____ dramatically over the last decade.", ["has changed", "changed", "is changing", "had changed"], 0, "Present perfect is used with over the last decade up to the present."],
  ["Tense & aspect", "Before moving abroad, he _____ in the same town all his life.", ["had lived", "has lived", "was living", "lived"], 0, "Past perfect refers to an earlier period before moving."],

  ["Articles & determiners", "She gave a remarkable presentation on _____ role of trust in teams.", ["the", "a", "an", "no article"], 0, "The identifies the specific role being discussed."],
  ["Articles & determiners", "This is _____ first time I have used the platform.", ["the", "a", "an", "no article"], 0, "Ordinal numbers such as first normally take the definite article."],
  ["Articles & determiners", "There is _____ evidence that the policy has worked.", ["no", "a", "an", "few"], 0, "Evidence is uncountable, so no evidence is the correct negative phrase."],
  ["Articles & determiners", "We have _____ time left, so we need to decide now.", ["little", "a few", "many", "several"], 0, "Little is used with uncountable time to mean not much."],
  ["Articles & determiners", "Only _____ people understood the technical explanation.", ["a few", "a little", "much", "every"], 0, "People is countable plural, so a few is appropriate."],
  ["Articles & determiners", "It was _____ honest mistake rather than deliberate misconduct.", ["an", "a", "the", "no article"], 0, "Honest begins with a vowel sound, so use an."],
  ["Articles & determiners", "The research was carried out in _____ Netherlands.", ["the", "a", "an", "no article"], 0, "Names of countries with a plural form or descriptive noun take the."],
  ["Articles & determiners", "Each of the participants _____ given a reference number.", ["was", "were", "have been", "are"], 0, "Each is singular and takes a singular verb."],
  ["Articles & determiners", "Neither answer _____ completely satisfactory.", ["is", "are", "have been", "were"], 0, "Neither is singular in this formal construction."],
  ["Articles & determiners", "A number of applicants _____ asked to attend a second interview.", ["have been", "has been", "is", "was"], 0, "A number of + plural noun takes a plural verb."],
  ["Articles & determiners", "The number of applicants _____ increased this year.", ["has", "have", "are", "were"], 0, "The number is a singular subject."],
  ["Articles & determiners", "The revised report contains _____ more information than the first version.", ["much", "many", "a few", "several"], 0, "Information is uncountable, so much is used."],
  ["Articles & determiners", "The new system has resulted in _____ mistakes.", ["fewer", "less", "much", "little"], 0, "Mistakes is countable plural, so fewer is correct."],
  ["Articles & determiners", "Every student _____ complete the safety briefing.", ["must", "are", "have", "were"], 0, "Every is followed by a singular noun and a singular subject or modal."],
  ["Articles & determiners", "We need _____ reason before changing the schedule.", ["another", "other", "others", "the others"], 0, "Another is used with a singular countable noun meaning one more."],
  ["Articles & determiners", "The government should provide more support for _____ elderly.", ["the", "an", "a", "no article"], 0, "The + adjective refers to a whole social group."],
  ["Articles & determiners", "Most of _____ equipment was replaced last year.", ["the", "a", "an", "no article"], 0, "The specific equipment is uncountable and takes the."],
  ["Articles & determiners", "_____ increasing number of workers are choosing flexible hours.", ["An", "A", "The", "No article"], 0, "An precedes increasing because it begins with a vowel sound."],
  ["Articles & determiners", "Could you give me _____ advice about the interview?", ["some", "an", "a", "many"], 0, "Advice is uncountable and can be used with some."],
  ["Articles & determiners", "All _____ information in the briefing was accurate.", ["the", "a", "an", "many"], 0, "The information is a specific uncountable set already identified."],

  ["Relative & participle clauses", "The report, _____ was published yesterday, has already been updated.", ["which", "that", "what", "where"], 0, "Which introduces a non-defining relative clause after a comma."],
  ["Relative & participle clauses", "The scientist _____ research changed the field received an award.", ["whose", "who", "which", "where"], 0, "Whose expresses possession before the noun research."],
  ["Relative & participle clauses", "The town _____ the conference was held has limited hotel space.", ["where", "which", "whose", "what"], 0, "Where refers to the place in which the conference was held."],
  ["Relative & participle clauses", "_____ surprised me most was the speed of the recovery.", ["What", "Which", "That", "Where"], 0, "What introduces a noun clause meaning the thing that."],
  ["Relative & participle clauses", "_____ arrives first should reserve the room.", ["Whoever", "Which", "What", "Where"], 0, "Whoever means any person who and acts as the subject."],
  ["Relative & participle clauses", "_____ the final draft, she sent it to the editor.", ["Having finished", "Finished", "To finish", "Finish"], 0, "Having finished shows the first action was completed before the second."],
  ["Relative & participle clauses", "_____ by the long journey, the hikers rested immediately.", ["Exhausted", "Exhausting", "Having exhaust", "To exhaust"], 0, "The past participle describes the hikers' state."],
  ["Relative & participle clauses", "_____ to reduce waste, the system records every purchase.", ["Designed", "Designing", "Having design", "To designing"], 0, "Designed is a reduced passive clause describing the system."],
  ["Relative & participle clauses", "The people _____ next door are professional musicians.", ["living", "lived", "to live", "are living"], 0, "A present participle can reduce who live next door."],
  ["Relative & participle clauses", "The report, _____ includes three recommendations, will be discussed tomorrow.", ["which", "what", "where", "whose"], 0, "Which introduces a non-defining clause referring to the report."],
  ["Relative & participle clauses", "The book _____ you recommended was out of print.", ["that", "what", "where", "whose"], 0, "That can introduce a defining relative clause referring to a thing."],
  ["Relative & participle clauses", "The reason _____ the project failed remains unclear.", ["why", "which", "what", "where"], 0, "Why is the standard relative adverb after reason."],
  ["Relative & participle clauses", "Anyone _____ to join should complete the registration form.", ["wishing", "wished", "to wishing", "is wishing"], 0, "Wishing reduces anyone who wishes to join."],
  ["Relative & participle clauses", "Once _____, the form cannot be edited.", ["submitted", "submitting", "to submit", "it submitting"], 0, "Submitted is a reduced passive clause."],
  ["Relative & participle clauses", "_____ the circumstances, the committee postponed the vote.", ["Given", "Giving", "To give", "Having give"], 0, "Given the circumstances is a fixed participle phrase meaning considering."],
  ["Relative & participle clauses", "The company for _____ I work is expanding rapidly.", ["which", "where", "what", "whose"], 0, "For which is the formal relative form referring to the company."],
  ["Relative & participle clauses", "The issue about _____ they argued was eventually resolved.", ["which", "what", "where", "whose"], 0, "A preposition + which is used for a thing in formal English."],
  ["Relative & participle clauses", "_____ the committee decided will affect the entire department.", ["What", "Which", "Where", "Who"], 0, "What introduces the subject noun clause."],
  ["Relative & participle clauses", "_____ by tall trees, the house is difficult to see from the road.", ["Surrounded", "Surrounding", "To surround", "Having surround"], 0, "Surrounded is a reduced passive clause describing the house."],
  ["Relative & participle clauses", "Rather than _____ the original plan, the team adapted it.", ["abandoning", "to abandon", "abandoned", "abandon"], 0, "Rather than is followed by a gerund when contrasting activities."],

  ["Linkers & discourse", "_____ being expensive, the device is remarkably reliable.", ["Despite", "Although", "However", "Because"], 0, "Despite is followed by a noun or gerund phrase."],
  ["Linkers & discourse", "_____ he was tired, he continued working.", ["Although", "Despite", "Nevertheless", "In spite"], 0, "Although introduces a clause with a subject and verb."],
  ["Linkers & discourse", "The first plan is cheap, _____ the second is more sustainable.", ["whereas", "despite", "nevertheless", "because of"], 0, "Whereas contrasts two clauses or situations."],
  ["Linkers & discourse", "The evidence was limited. _____, the committee approved the proposal.", ["Nevertheless", "Despite", "Although", "Because"], 0, "Nevertheless links two contrasting independent statements."],
  ["Linkers & discourse", "_____ the delay, the team delivered the project on time.", ["In spite of", "Although", "Nevertheless", "Even though"], 0, "In spite of is followed by a noun phrase."],
  ["Linkers & discourse", "You may use the laboratory _____ you follow the safety rules.", ["provided that", "despite", "whereas", "in spite"], 0, "Provided that introduces a condition."],
  ["Linkers & discourse", "The instructions were simplified _____ more users could understand them.", ["so that", "despite", "whereas", "nevertheless"], 0, "So that introduces a purpose clause with a subject and verb."],
  ["Linkers & discourse", "The team met early _____ prepare the presentation.", ["in order to", "so that", "despite", "whereas"], 0, "In order to is followed by a base verb to express purpose."],
  ["Linkers & discourse", "The road was closed; _____, the delivery arrived on time.", ["as a result", "however", "because", "therefore of"], 1, "However expresses contrast between the closure and the successful delivery."],
  ["Linkers & discourse", "The proposal is ambitious. _____, it is financially realistic.", ["On the other hand", "Because", "Despite", "In order to"], 0, "On the other hand introduces a contrasting consideration."],
  ["Linkers & discourse", "The plan will work _____ everyone follows the timetable.", ["as long as", "despite", "whereas", "nevertheless"], 0, "As long as introduces a condition."],
  ["Linkers & discourse", "_____ cost, the two options are almost identical.", ["In terms of", "Although", "Nevertheless", "Despite of"], 0, "In terms of introduces the aspect being compared."],
  ["Linkers & discourse", "_____ the new timetable, staff will need to arrive earlier.", ["With regard to", "Although", "Despite", "However"], 0, "With regard to means concerning and is followed by a noun phrase."],
  ["Linkers & discourse", "_____ attending the lecture, she read the transcript.", ["In addition to", "Although", "Nevertheless", "Because"], 0, "In addition to is followed by a noun or gerund."],
  ["Linkers & discourse", "The course is _____ practical _____ intellectually demanding.", ["not only / but also", "both / than", "rather / and", "neither / or"], 0, "Not only ... but also links two parallel qualities."],
  ["Linkers & discourse", "_____ you practise, the more fluent you become.", ["The more", "More", "As more", "Much more"], 0, "The comparative correlative uses the more ... the more."],
  ["Linkers & discourse", "He looked at me _____ he had never seen me before.", ["as if", "despite", "whereas", "so that"], 0, "As if introduces an imagined comparison."],
  ["Linkers & discourse", "_____ the budget was reduced, the project continued.", ["Even though", "In spite", "Nevertheless", "Despite of"], 0, "Even though introduces a concessive clause."],
  ["Linkers & discourse", "By the time we arrived, the presentation _____.", ["had begun", "has begun", "began", "was beginning"], 0, "By the time in a past context is followed by past perfect for the earlier action."],
  ["Linkers & discourse", "The results are encouraging, _____ further research is needed.", ["although", "despite", "because of", "in order to"], 0, "Although introduces a contrasting clause."],

  ["Passive & reporting", "The new policy _____ to reduce waiting times.", ["is believed", "believes", "is believing", "has believed"], 0, "The passive reporting structure is believed to + infinitive."],
  ["Passive & reporting", "The researcher _____ to have discovered a new treatment.", ["is thought", "thinks", "is thinking", "has thought"], 0, "Is thought to have discovered reports an earlier action."],
  ["Passive & reporting", "Several laptops _____ during the move.", ["had been stolen", "had stolen", "were stealing", "have stealing"], 0, "Past perfect passive is used for an earlier completed theft."],
  ["Passive & reporting", "I need to get my passport _____.", ["renewed", "renew", "renewing", "to renew"], 0, "Get + object + past participle means arrange for a service."],
  ["Passive & reporting", "All staff _____ informed about the change before the meeting.", ["had been", "had", "were being", "have"], 0, "Past perfect passive uses had been + past participle."],
  ["Passive & reporting", "The witness was made _____ a statement.", ["to give", "give", "giving", "given"], 0, "Make in the passive is followed by to + infinitive."],
  ["Passive & reporting", "The results _____ to be published next week.", ["are expected", "expect", "are expecting", "have expected"], 0, "Are expected to expresses a reported expectation."],
  ["Passive & reporting", "Several alternatives _____ being considered by the board.", ["are", "have", "were", "is"], 0, "Present continuous passive uses are being + past participle."],
  ["Passive & reporting", "It _____ that the company will expand overseas.", ["has been reported", "has reported", "is reporting", "was reporting"], 0, "It has been reported that is an impersonal passive reporting structure."],
  ["Passive & reporting", "The proposal was said _____ too expensive.", ["to be", "being", "be", "to have"], 0, "Was said to be reports a simultaneous state."],
  ["Passive & reporting", "The application _____ by Friday at the latest.", ["should be submitted", "should submit", "should have submitting", "should be submitting"], 0, "Should be submitted is a modal passive."],
  ["Passive & reporting", "The region _____ for its excellent public transport.", ["is known", "knows", "is knowing", "has known"], 0, "Is known for is a passive collocation."],
  ["Passive & reporting", "Each participant was given a certificate _____ the end of the course.", ["at", "on", "in", "by"], 0, "At the end of is the correct time expression."],
  ["Passive & reporting", "We had the documents _____ into three languages.", ["translated", "translate", "translating", "to translate"], 0, "Have + object + past participle expresses an arranged service."],
  ["Passive & reporting", "She got _____ after leading the successful project.", ["promoted", "promote", "promoting", "to promote"], 0, "Get + past participle can describe an event affecting the subject."],
  ["Passive & reporting", "The old batteries need to _____.", ["be replaced", "replace", "replacing", "have replaced"], 0, "Need to be replaced is a passive necessity."],
  ["Passive & reporting", "The patient's condition is _____ monitored.", ["being", "been", "be", "having"], 0, "Is being monitored is the present continuous passive."],
  ["Passive & reporting", "The cause of the outage has yet _____ determined.", ["to be", "being", "been", "be"], 0, "Has yet to be determined means it has not been determined so far."],
  ["Passive & reporting", "The painting is believed _____ stolen during the war.", ["to have been", "to be", "being", "have"], 0, "To have been stolen refers to an earlier passive event."],
  ["Passive & reporting", "Let it _____ that late applications will not be accepted.", ["be known", "known", "to know", "be knowing"], 0, "Let it be known is a fixed passive expression."],

  ["Collocations & prepositions", "The director is responsible _____ approving the final budget.", ["for", "to", "of", "with"], 0, "Responsible is followed by for."],
  ["Collocations & prepositions", "The device is capable _____ detecting small changes in pressure.", ["of", "to", "for", "with"], 0, "Capable is followed by of + gerund or noun."],
  ["Collocations & prepositions", "The union insisted _____ seeing the full contract.", ["on", "to", "for", "with"], 0, "Insist on is followed by a noun or gerund."],
  ["Collocations & prepositions", "Several residents objected _____ the proposed development.", ["to", "for", "with", "on"], 0, "Object is followed by to."],
  ["Collocations & prepositions", "The outcome depends _____ how quickly the team responds.", ["on", "of", "for", "with"], 0, "Depend is followed by on."],
  ["Collocations & prepositions", "All suppliers must comply _____ the new regulations.", ["with", "to", "for", "on"], 0, "Comply is followed by with."],
  ["Collocations & prepositions", "Students can benefit _____ regular feedback.", ["from", "of", "to", "with"], 0, "Benefit is followed by from when meaning gain an advantage."],
  ["Collocations & prepositions", "The company was accused _____ misleading customers.", ["of", "for", "to", "with"], 0, "Accused is followed by of + gerund or noun."],
  ["Collocations & prepositions", "It is difficult to distinguish _____ fact and opinion.", ["between", "among", "from", "with"], 0, "Distinguish between is used for two contrasting things."],
  ["Collocations & prepositions", "The scheme will contribute _____ reducing energy use.", ["to", "for", "with", "on"], 0, "Contribute to is followed by a noun or gerund."],
  ["Collocations & prepositions", "We should take advantage _____ the quieter season.", ["of", "from", "to", "with"], 0, "Take advantage is followed by of."],
  ["Collocations & prepositions", "I cannot put up _____ that level of noise every night.", ["with", "to", "for", "on"], 0, "Put up with means tolerate."],
  ["Collocations & prepositions", "The auditors will carry _____ a detailed review.", ["out", "on", "over", "up"], 0, "Carry out means perform or complete a task."],
  ["Collocations & prepositions", "The reform brought _____ significant improvements.", ["about", "out", "up", "over"], 0, "Bring about means cause something to happen."],
  ["Collocations & prepositions", "The committee will look _____ the complaint.", ["into", "after", "for", "up"], 0, "Look into means investigate."],
  ["Collocations & prepositions", "I came _____ an interesting article while researching the topic.", ["across", "into", "over", "up"], 0, "Come across means find by chance."],
  ["Collocations & prepositions", "The campaign aims to cut down _____ plastic packaging.", ["on", "of", "with", "to"], 0, "Cut down on means reduce consumption of something."],
  ["Collocations & prepositions", "The final paragraph accounts _____ most of the word count.", ["for", "to", "of", "with"], 0, "Account for means make up a proportion of something."],
  ["Collocations & prepositions", "Older buildings are more prone _____ damp.", ["to", "for", "of", "with"], 0, "Prone is followed by to."],
  ["Collocations & prepositions", "The changes were made in accordance _____ the agreement.", ["with", "to", "for", "on"], 0, "In accordance with means consistently with a rule or agreement."],
];

window.grammarQuestions = grammarBank.map(([category, prompt, options, answer, explanation], index) => {
  const level = index % 20 < 10 ? 'C1' : 'B2';
  return {
    id: index + 1,
    category,
    level,
    difficulty: level === 'C1' ? 'High' : 'Medium',
    prompt,
    options,
    answer,
    explanation
  };
});
